### ISSUE TITLE
This Fatal Error

### ISSUE THREAD

**Issue by SergioFloresG** [syllant/idea-plugin-xstructure#12]
com/intellij/openapi/actionSystem/DataKeys

```
com/intellij/openapi/actionSystem/DataKeys
java.lang.NoClassDefFoundError: com/intellij/openapi/actionSystem/DataKeys
	at org.sylfra.idea.plugins.xstructure.actions.SelectMappingSetAction.retrieveXmlFile(SelectMappingSetAction.java:74)
	at org.sylfra.idea.plugins.xstructure.actions.SelectMappingSetAction.createPopupActionGroup(SelectMappingSetAction.java:43)
	at com.intellij.openapi.actionSystem.ex.ComboBoxAction.createPopupActionGroup(ComboBoxAction.java:135)
	at com.intellij.openapi.actionSystem.ex.ComboBoxAction.createActionPopup(ComboBoxAction.java:90)
	at com.intellij.openapi.actionSystem.ex.ComboBoxAction.access$300(ComboBoxAction.java:50)
	at com.intellij.openapi.actionSystem.ex.ComboBoxAction$ComboBoxButton.createPopup(ComboBoxAction.java:283)
	at com.intellij.openapi.actionSystem.ex.ComboBoxAction$ComboBoxButton.showPopup(ComboBoxAction.java:279)
	at com.intellij.openapi.actionSystem.ex.ComboBoxAction$ComboBoxButton$1.lambda$actionPerformed$0(ComboBoxAction.java:182)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.a(FocusManagerImpl.java:643)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.o(FocusManagerImpl.java:624)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.m(FocusManagerImpl.java:594)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.a(FocusManagerImpl.java:476)
	at com.intellij.util.ui.UIUtil.invokeLaterIfNeeded(UIUtil.java:2760)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.doWhenFocusSettlesDown(FocusManagerImpl.java:456)
	at com.intellij.openapi.actionSystem.ex.ComboBoxAction$ComboBoxButton$1.actionPerformed(ComboBoxAction.java:182)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:356)
	at com.intellij.openapi.actionSystem.ex.ComboBoxAction$ComboBoxButton$2.mousePressed(ComboBoxAction.java:206)
	at java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:280)
	at java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:279)
	at java.awt.Component.processMouseEvent(Component.java:6538)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6306)
	at java.awt.Container.processEvent(Container.java:2237)
	at java.awt.Component.dispatchEventImpl(Component.java:4897)
	at java.awt.Container.dispatchEventImpl(Container.java:2295)
	at java.awt.Component.dispatchEvent(Component.java:4719)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4523)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467)
	at java.awt.Container.dispatchEventImpl(Container.java:2281)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4719)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.awt.EventQueue$4.run(EventQueue.java:735)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.k(IdeEventQueue.java:822)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:646)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:366)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by aand18** [comment]
any news on this?

**Comment by syllant** [comment]
When I have details (product, product version, plugin version).
