### ISSUE TITLE
NoClassDefFoundError: com/intellij/openapi/actionSystem/DataKeys

### ISSUE THREAD

**Issue by fenders** [syllant/idea-plugin-xstructure#9]
Hey guys,

using xStructure 1.5.1 with both, WebStorm 8.0.1 and 8.0.3, throws an error when clicking on the xStructure dropdown within the structure window. 
Besides, a structure is getting displayed but looks like before having installed the xStructure plugin. 

Stacktrace follows.

Any idea? 
Thanks and all the best
Frank

```
com/intellij/openapi/actionSystem/DataKeys: com/intellij/openapi/actionSystem/DataKeys
java.lang.NoClassDefFoundError: com/intellij/openapi/actionSystem/DataKeys
    at org.sylfra.idea.plugins.xstructure.actions.SelectMappingSetAction.retrieveXmlFile(SelectMappingSetAction.java:74)
    at org.sylfra.idea.plugins.xstructure.actions.SelectMappingSetAction.createPopupActionGroup(SelectMappingSetAction.java:43)
    at com.intellij.openapi.actionSystem.ex.ComboBoxAction$ComboBoxButton.createPopup(ComboBoxAction.java:238)
    at com.intellij.openapi.actionSystem.ex.ComboBoxAction$ComboBoxButton.showPopup(ComboBoxAction.java:227)
    at com.intellij.openapi.actionSystem.ex.ComboBoxAction$ComboBoxButton$1$1.run(ComboBoxAction.java:130)
    at com.intellij.openapi.wm.impl.FocusManagerImpl.a(FocusManagerImpl.java:651)
    at com.intellij.openapi.wm.impl.FocusManagerImpl.g(FocusManagerImpl.java:632)
    at com.intellij.openapi.wm.impl.FocusManagerImpl.e(FocusManagerImpl.java:602)
    at com.intellij.openapi.wm.impl.FocusManagerImpl.access$200(FocusManagerImpl.java:60)
    at com.intellij.openapi.wm.impl.FocusManagerImpl$7.run(FocusManagerImpl.java:498)
    at com.intellij.util.ui.UIUtil.invokeLaterIfNeeded(UIUtil.java:2053)
    at com.intellij.openapi.wm.impl.FocusManagerImpl.doWhenFocusSettlesDown(FocusManagerImpl.java:476)
    at com.intellij.openapi.actionSystem.ex.ComboBoxAction$ComboBoxButton$1.actionPerformed(ComboBoxAction.java:127)
    at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2018)
    at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2341)
    at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
    at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
    at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
    at javax.swing.AbstractButton.doClick(AbstractButton.java:356)
    at com.intellij.openapi.actionSystem.ex.ComboBoxAction$ComboBoxButton$2.mousePressed(ComboBoxAction.java:156)
    at java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:280)
    at java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:279)
    at java.awt.Component.processMouseEvent(Component.java:6502)
    at javax.swing.JComponent.processMouseEvent(JComponent.java:3320)
    at java.awt.Component.processEvent(Component.java:6270)
    at java.awt.Container.processEvent(Container.java:2229)
    at java.awt.Component.dispatchEventImpl(Component.java:4861)
    at java.awt.Container.dispatchEventImpl(Container.java:2287)
    at java.awt.Component.dispatchEvent(Component.java:4687)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4832)
    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4489)
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4422)
    at java.awt.Container.dispatchEventImpl(Container.java:2273)
    at java.awt.Window.dispatchEventImpl(Window.java:2719)
    at java.awt.Component.dispatchEvent(Component.java:4687)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:735)
    at java.awt.EventQueue.access$200(EventQueue.java:103)
    at java.awt.EventQueue$3.run(EventQueue.java:694)
    at java.awt.EventQueue$3.run(EventQueue.java:692)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:87)
    at java.awt.EventQueue$4.run(EventQueue.java:708)
    at java.awt.EventQueue$4.run(EventQueue.java:706)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:705)
    at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:697)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:520)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:335)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
Caused by: java.lang.ClassNotFoundException: com.intellij.openapi.actionSystem.DataKeys PluginClassLoader[org.sylfra.idea.plugins.xstructure, 1.5.1]
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:68)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 56 more
```

**Comment by vovchynniko** [comment]
Similar issue from another plugin: https://github.com/syllant/idea-plugin-remotesynchronizer/issues/6

**Comment by syllant** [comment]
Thanks for reporting, I'll try to fix this one in the next days.
